name:                tutorial
version:             0.1.0.0
github:              "coltonkinstley/tutorial"
license:             BSD3
author:              "Colton Kinstley"
maintainer:          "haskell@coltonkinstley.com"
copyright:           "Colton Kinstley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            tutorial

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coltonkinstley/tutorial#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tutorial-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tutorial

tests:
  tutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tutorial
